# Simple query to get 10 items with labels
# Wikidata SPARQL query - works with https://query.wikidata.org/sparql

SELECT ?item ?itemLabel WHERE {
  ?item wdt:P31 wd:Q5 .  # humans
  ?item wdt:P106 wd:Q82955 .  # politicians
  
  SERVICE wikibase:label { bd:serviceParam wikibase:language "en" }
}
LIMIT 10